# Application configuration
spring:
  application:
    name: stock-price-download

  # Set active profiles
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Logging configuration
logging:
  level:
    root: INFO
    com.darylmathison.market: DEBUG
    org.springframework: INFO

# Custom application properties
data:
  bucket:
    name: ${DATA_BUCKET}
  symbols:
    file: ${SYMBOLS:symbols.txt}
    batch-size: ${SYMBOLS_BATCH_SIZE:6000}
history:
  days: ${HISTORY_DAYS:5}
alpaca:
  apikey: ${ALPACA_API_KEY}
  secret: ${ALPACA_SECRET_KEY}

aws:
  region: ${AWS_REGION}


---
# Development profile
spring:
  config:
    activate:
      on-profile: dev

# Add dev-specific configurations here if needed

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod

# Add production-specific configurations here
